<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-05T20:41:40 EET" name="Suite" finished-at="2023-03-05T20:42:04 EET" duration-ms="23758">
    <groups>
      <group name="Smoke">
        <method signature="ECommerceTestCase1.fillForm()[pri:0, instance:mertkanCompany.ECommerceTestCase1@3f91b517]" name="fillForm" class="mertkanCompany.ECommerceTestCase1"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2023-03-05T20:41:40 EET" name="End to end framework test" finished-at="2023-03-05T20:41:40 EET" duration-ms="35">
    </test> <!-- End to end framework test -->
    <test started-at="2023-03-05T20:41:40 EET" name="Error validations test" finished-at="2023-03-05T20:42:04 EET" duration-ms="23660">
      <class name="mertkanCompany.ECommerceTestCase1">
        <test-method is-config="true" signature="configureAppium()[pri:0, instance:mertkanCompany.ECommerceTestCase1@3f91b517]" started-at="2023-03-05T20:41:40 EET" name="configureAppium" finished-at="2023-03-05T20:41:58 EET" duration-ms="17639" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configureAppium -->
        <test-method signature="fillForm()[pri:0, instance:mertkanCompany.ECommerceTestCase1@3f91b517]" started-at="2023-03-05T20:41:58 EET" name="fillForm" finished-at="2023-03-05T20:42:02 EET" duration-ms="4582" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please  your name] but found [Please enter your name]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please  your name] but found [Please enter your name]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at mertkanCompany.ECommerceTestCase1.fillForm(ECommerceTestCase1.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fillForm -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:mertkanCompany.ECommerceTestCase1@3f91b517]" started-at="2023-03-05T20:42:03 EET" name="tearDown" finished-at="2023-03-05T20:42:04 EET" duration-ms="838" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- mertkanCompany.ECommerceTestCase1 -->
    </test> <!-- Error validations test -->
  </suite> <!-- Suite -->
</testng-results>
